apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

resources:
  - jupyterhub-ingress.yaml

patchesStrategicMerge:
  - jupyterhub-db-dc.yaml


commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub


# configMapGenerator:
# - name: parameters
#   behavior: merge
#   env: params.env
# generatorOptions:
#   disableNameSuffixHash: true
# vars:
# - name: JUPYTERHUB_HOST
#   objref:
#     kind: ConfigMap
#     name: parameters
#     apiVersion: v1
#   fieldref:
#     fieldpath: data.JUPYTERHUB_HOST
# configurations:
# - params.yaml