apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

resources:
  - jupyterhub-ingress.yaml

patchesStrategicMerge:
  - jupyterhub-db-dc.yaml


commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub


configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: jupyterhub-cfg
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: storage_class
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.storage_class
- name: s3_endpoint_url
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3_endpoint_url
- name: jupyterhub_groups_config
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.jupyterhub_groups_config
- name: jupyterhub_secret
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.jupyterhub_secret
- name: KEYCLOAK_URL
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.KEYCLOAK_URL
- name: CLIENT_SECRET
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.CLIENT_SECRET
- name: JUPYTERHUB_HOST
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.JUPYTERHUB_HOST
configurations:
- params.yaml
