apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterhub
  labels:
    app: jupyterhub
  annotations:
    openshift.io/host.generated: 'true'
spec:
  tls:
    - hosts:
      - $(JUPYTERHUB_HOST)

  rules:
  - host: $(JUPYTERHUB_HOST)
    http:
      paths:
      - backend:
          service:
            name: jupyterhub
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific  