apiVersion: v1
kind: LimitRange
metadata:
  name: ml-workshop-limit-range
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 750m
    defaultRequest:
      memory: 350Mi
      cpu: 75m
    type: Container