apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - subscription.yaml
  - prometheus.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "prometheus"



