apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-flights-data
  labels:
    app: pg-flights-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-flights-data
  template:
    metadata:
      labels:
        app: pg-flights-data
    spec:
      containers:
      - name: postgres
        image: quay.io/rbrigoli/flights-data:4.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432