apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-flights-data
  labels:
    app: pg-flights-data
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-flights-data
  template:
    metadata:
      labels:
        app: pg-flights-data
    spec:
      containers:
      - name: postgres
        image: quay.io/ml-on-k8s/flights-data
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432