apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
  - image-stream-crd.yaml
  - route-crd.yaml

commonLabels:
  opendatahub.io/component: "true"
