apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    project_name: {{  model_name }}
    deployment_version: {{  experiment_id }}
  labels:
    app: seldon
  name: model-{{  experiment_id }}

spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: model-{{  experiment_id }}-{{ model_name }}
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific  



